export const cars = [
  {
    image: 'maserati_PNG15.png',
    name: 'Maserati MC20 Cielo',
    price: '$1200',
    category: 'Luxury',
    seats: '2',
    transmision: 'Manual',
    speed: '346/Kmh',
    w: 122,
    h: 250,
  },
  {
    image: 'bmw_PNG1695.png',
    name: 'BMW M3 Series Sedan',
    price: '$999',
    category: 'Premium',
    seats: '2',
    transmision: 'Automatic',
    speed: '306/Kmh',
    w: 188,
    h: 250,
  },
  {
    image: 'audi-yellow.png',
    name: 'Audi A6 2020',
    price: '$899',
    category: 'Premium',
    seats: '4',
    transmision: 'Automatic',
    speed: '280/Kmh',
    w: 142,
    h: 250,
  },
  {
    image: '',
    name: '',
    price: '',
    category: '',
    seats: '',
    transmision: '',
    speed: '',
    w: '',
    h: '',
  },
];

export const recentCars = [
  {
    width: 300,
    carId: 'hnd78ysdiuaha8927ssw',
    name: 'Honda Accord Sedan',
    transmision: 'Automatic',
    location: 'Jakarta',
    category: 'Premium',
    currency: 'USD',
    speed: '280/Kmh',
    brand: 'Honda',
    seat: 4,
    cost: 199,
    urlImage: '/image/honda_PNG10330.png',
    height: 225,
  },
  {
    brand: 'Toyota',
    category: 'Premium',
    location: 'Jakarta',
    width: 350,
    carId: 'tyt45sfs7s72',
    cost: 900000,
    height: 180,
    name: 'Toyota Camry',
    transmision: 'Automatic',
    seat: 4,
    currency: 'IDR',
    urlImage: '/image/toyota_PNG1947.png',
    speed: '225/Kmh',
  },
  {
    currency: 'USD',
    width: 310,
    seat: 4,
    category: 'Premium',
    urlImage: '/image/audi-a6000.png',
    speed: '286/Kmh',
    height: 150,
    cost: 700,
    transmision: 'Automatic',
    location: 'Jakarta',
    carId: 'aud72292h9ud91whhs',
    brand: 'Audi',
    name: 'Audi A6000',
  },
  {
    name: 'Honda CR-V Black Edition',
    category: 'SUV',
    currency: 'IDR',
    urlImage: '/image/honda_crv_BE.png',
    cost: 320000,
    transmision: 'Automatic',
    seat: 6,
    location: 'Surabaya',
    speed: '205/Kmh',
    width: 350,
    carId: 'hnd62625crw910',
    brand: 'Honda',
    height: 215,
  },
  {
    transmision: 'Manual',
    seat: 4,
    speed: '140/Kmh',
    width: 350,
    name: 'Toyota Sienta 2016',
    location: 'Surabaya',
    height: 233,
    carId: 'tyt92hi281gg',
    brand: 'Toyota',
    currency: 'IDR',
    urlImage: '/image/toyota_sienta_2006.png',
    cost: 199000,
    category: 'Family car',
  },
  {
    name: 'Audi A3 Yellow Edition',
    transmision: 'Manual',
    seat: 2,
    category: 'Luxury',
    currency: 'USD',
    speed: '306/Kmh',
    width: 320,
    brand: 'Audi',
    height: 180,
    carId: 'aud7yy722ggy2819',
    cost: 1009,
    location: 'Jakarta',
    urlImage: '/image/audi-yellow.png',
  },
  {
    currency: 'IDR',
    width: 310,
    cost: 300,
    seat: 6,
    urlImage: '/image/honda_crv.png',
    name: 'Honda CR-V',
    brand: 'Honda',
    transmision: 'Automatic',
    location: 'Surabaya',
    category: 'SUV',
    speed: '190/Kmh',
    carId: 'hnd77182uhhrg1545',
    height: 200,
  },
  {
    carId: 'hwiwi782215gg',
    name: 'Mitsubishi Xpander',
    brand: 'Mitsubishi',
    category: 'SUV',
    currency: 'IDR',
    urlImage: '/image/mitsubishi_xpander.png',
    speed: '250/Kmh',
    width: 331,
    cost: 350000,
    seat: 6,
    transmision: 'Automatic',
    location: 'Surabaya',
    height: 185,
  },
  {
    transmision: 'Auotomatic',
    currency: 'USD',
    speed: '309/Kmh',
    width: 300,
    carId: 'uyg3lp112jfff',
    seat: 2,
    location: 'Jakarta',
    category: 'Premium',
    height: 210,
    name: 'BMW M3',
    cost: 999,
    brand: 'BMW',
    urlImage: '/image/bmw_M3.png',
  },
  {
    name: 'Toyota Avanza',
    cost: 225000,
    transmision: 'Manual',
    seat: 4,
    width: 298,
    urlImage: '/image/toyota_avanza.png',
    carId: 'tyt76shsjsk33782g2',
    brand: 'Toyota',
    category: 'Family Car',
    speed: '160/Kmh',
    height: 230,
    location: 'Surabaya',
    currency: 'IDR',
  },
  {
    cost: 349000,
    urlImage: '/image/mitsubishi_outlander-sport.png',
    transmision: 'Manual',
    seat: 4,
    location: 'Jakarta',
    name: 'Mitsubishi Outlander Sport',
    speed: '180/Kmh',
    width: 330,
    height: 178,
    carId: 'msbs7t568asjkks',
    brand: 'Mitsubishi',
    category: 'Family car',
    currency: 'IDR',
  },
  {
    height: 193,
    cost: 579,
    width: 265,
    seat: 6,
    urlImage: '/image/merci_gle_suv.png',
    speed: '225/Kmh',
    transmision: 'Automatic',
    name: 'Mercedes GLE SUV',
    brand: 'Mercedes',
    location: 'Bali',
    category: 'SUV',
    currency: 'USD',
    carId: 'mrcs54a812902hj2kk',
  },
  {
    carId: 'msrt892kjkj2hgysi',
    location: 'Jakarta',
    urlImage: '/image/maserati_PNG15.png',
    speed: '346/Kmh',
    name: 'Maserati MC20 Cielo',
    cost: 2299,
    brand: 'Maserati',
    width: 280,
    transmision: 'Manual',
    seat: 2,
    category: 'Luxury',
    currency: 'USD',
    height: 136,
  },
];
